package excepcionesEjerciciones;


public class ManejoExcepciones {
	private int a;
	private int b;
	
	
	public void main (String[]args)throws ArithmeticException {
		
		try {
			System.out.println("El resultado es: ");
			Calcular(300,0);	
		
		}finally{
			System.out.println("Programa finalizado");
			
		}
		
	}
	public void Calcular(int num1,int num2) {
		this.a=num1;
		this.b=num2;
		int result=num1/num2;
		System.out.println(result);
		
				
	}

}
